name: Build Plugin
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sm-version: ["1.10.x"]

    name: SM version ${{ matrix.sm-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup SourcePawn
        uses: rumblefrog/setup-sp@master
        with:
          version: ${{ matrix.sm-version }}

      - name: Execute build script
        run: |
          chmod +x tools/build.sh
          ./tools/build.sh

      - name: Get the version
        id: get_version
        if: startsWith(github.ref, 'refs/tags/')
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Upload Build
        uses: actions/upload-artifact@v2
        with:
          name: OnlyMySteamGroup_${{ matrix.sm-version }}
          path: build/

      - name: Prepare release
        run: |
          ls -alh .

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files:
            OnlyMySteamGroup_${{ steps.get_version.outputs.VERSION }}.zip
