name: Build Plugin
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sm-version: ["1.10.x"]

    name: SM version ${{ matrix.sm-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup SourcePawn
        uses: rumblefrog/setup-sp@master
        with:
          version: ${{ matrix.sm-version }}

      - name: Build OnlyMySteamGroup
        run: |
          spcomp scripting/onlymysteamgroup.sp

      - name: Execute build script
        run: |
          ./tools/build.sh
        env:
          includePath: /opt/hostedtoolcache/sourcepawn/1.10.6524/x64/include

      - name: Upload Build
        uses: actions/upload-artifact@v2
        with:
          name: OnlyMySteamGroup_${{ matrix.sm-version }}
          path: build/

      - name: Prepare
        run: |
          ls -alh .

      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   if: startsWith(github.ref, 'refs/tags/')
